### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by krisdb2009** [belowaverage-org/SuperStart#5]
- [x] Chrome wont re-launch for some reason.
- [x] Make some sort of visual indicator when waiting on a process to start.
- [x] Do something other than freeze when waiting for a process to start after pin is inserted.
- [x] Enable visual styles.
- [x] Disable entire form to prevent gifs from playing when hidden
